title: Interactive Pioneers Conventions
description: Coding Conventions and best practises for Interactive Pioneers
author: David Setz
baseurl: "/conventions"
markdown: redcarpet
google_analytics:
highlighter: pygments
## Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
